active_provider: groq
prompts:
  planning_template: 'User request: {user_input}


    Create a structured plan to accomplish this request safely.'
  system_prompt: 'You are OSCAR, an intelligent system automation assistant. Always
    respond with valid JSON containing: thoughts, plan, risk_level, confirm_prompt'
providers:
  groq:
    base_url: https://api.groq.com/openai/v1
    max_tokens: 2048
    model: openai/gpt-oss-120b
    retry_attempts: 3
    temperature: 0.1
    timeout: 30
  openai:
    base_url: https://api.openai.com/v1
    max_tokens: 2048
    model: gpt-4-turbo-preview
    retry_attempts: 3
    temperature: 0.1
    timeout: 30
safety:
  confirmation_required:
  - system files
  - registry
  - sudo
  - delete
  dangerous_patterns:
  - rm\s+-rf\s+/
  - dd\s+if=
  - 'format\s+c:'
  - del\s+/s\s+/q
